### ISSUE TITLE
Allow access to app for Turing folk from offsite

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/WimbledonPlanner#44]
Currently the Azure app is restricted to Turing IP addresses, but open to anyone trying to access it whilst at the Turing.

As a first pass to making the app accessible to Turing folk offsite, we'll incorporate Azure Active directory login.

Note that this is still fairly "hacky" as the app is accessing Github and Harvest with credentials many users with Turing AAD credentials will not have. See issue #50 as placeholder for improvements to authentication.

**Comment by jack89roberts** [comment]
The app registration expired and had to be renewed. These are the steps for renewing it:

- Create a ticket with IT asking them to renew the active directory app registration for Wimbledon Planner (I also included the redirect URL https://wimbledon-planner.azurewebsites.net/.auth/login/aad/callback and the previous ticket numbers C1910-085 and I2010-637).

- IT will send a new secret value.

- Update the `app-secret` secret in the `wimbledon-planner` key vault in the `wimbledon-planner-production` resource group.
  - Go to secrets (menu on the left)
  - Select `app-secret` from the list
  - Select "New Version"
  - Copy the secret into the "value" field and make sure to set the activation and expiration dates (these will cause an automated email to be triggered the next time it's about to expire).

- Update the secret value in the `wimbledon-planner` app service in the `wimbledon-planner-production` resource group.
  - Go to Authentication/Authorization (menu on the left)
  - Click on Azure Active Directory Configured (Advanced)
  - Click "Show Secret"
  - Paste the new secret value into the secret field.
  - Click "OK"

I then restarted the app service, but I'm not sure whether this is necessary.

**Comment by yongrenjie** [comment]
16/1/2024: Client secret was renewed. The steps are similar to above, but the Azure interface is slightly different:

1. Bug IT to send a new client secret
2. (Same as above) Go to the `wimbledon-planner` key vault in the `wimbledon-planner-production` resource group. From the left menu, select Objects > Secrets. Click on `app-secret` and create a new version
3. In the `wimbledon-planner` App Service, select Settings > Configuration, and select Application Settings from the tabs in that page. Click on `MICROSOFT_PROVIDER_AUTHENTICATION_SECRET` and paste the new secret as the value there.
  - You _can_ also do this from Settings > Authentication, and editing the `Wimbledon-Planner` identity provider in the list shown there. It brings you to the same screen.

Wait a couple of minutes and the app should work. I didn't need to restart it.

**Comment by jack89roberts** [comment]
Thanks Jon!
