### ISSUE TITLE
Update results in error

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/WimbledonPlanner#56]
I get the following error when clicking the "update" link.

>Traceback (most recent call last): File "app.py", line 117, in update capacity_fig = vis.plot_demand_vs_capacity() File "/WimbledonPlanner/wimbledon/vis/Visualise.py", line 539, in plot_demand_vs_capacity research_support_idx = self.wim.get_client_id('REG Support') File "/WimbledonPlanner/wimbledon/wimbledon.py", line 211, in get_client_id return self.clients.index[self.clients.name == client_name][0] File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4280, in __getitem__ return getitem(key) IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jack89roberts** [comment]
Hi Martin - this is now fixed. Thanks, Jack.
