### ISSUE TITLE
Capacity vs demand plot shows error

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/WimbledonPlanner#57]
I get the following eror when clicking on the "demand vs capacity" link.

>Traceback (most recent call last): File "app.py", line 244, in demand_vs_capacity return send_file(path) File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 588, in send_file file = open(filename, 'rb') FileNotFoundError: [Errno 2] No such file or directory: '/WimbledonPlanner/data/figs/demand_vs_capacity.png'

Possibly due to the update bug (#56) removing the image but not replacing it with a new one?

**Comment by jack89roberts** [comment]
The demand vs. capacity plot has now been updated to reflect changes to the client names on Forecast.

* REG Support is now REG Service Areas
* Turing Service Areas added
* Turing Programme Support added
* Not Funded projects added
