### ISSUE TITLE
pandas.datetime is deprecated

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/WimbledonPlanner#63]
Getting a lot of this:
> The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

Should swap to direct use of `datetime` as suggested.

**Comment by jack89roberts** [comment]
Done in #82

**Comment by jack89roberts** [comment]
@Prithivi-Raj Rather than e.g. `pd.datetime.now()` you should use the datetime library directly, e.g.
```
from datetime import datetime
datetime.now()
```

**Comment by Prithivi-Raj** [comment]
> @Prithivi-Raj Rather than e.g. `pd.datetime.now()` you should use the datetime library directly, e.g.
> 
> ```
> from datetime import datetime
> datetime.now()
> ```
Thank you so much
